AllCops:
  NewCops: enable

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - config/routes.rb

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb

Style/CollectionMethods:
  PreferredMethods:
    find: "detect"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
